# Generated by Django 2.1.5 on 2019-01-27 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('DOB', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('school', models.CharField(max_length=200)),
                ('phoneNum', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
