# Generated by Django 2.1.5 on 2019-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
