# Generated by Django 2.1.5 on 2019-01-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190126_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
